// Generated by gencpp from file do_math/Suan.msg
// DO NOT EDIT!


#ifndef DO_MATH_MESSAGE_SUAN_H
#define DO_MATH_MESSAGE_SUAN_H

#include <ros/service_traits.h>


#include <do_math/SuanRequest.h>
#include <do_math/SuanResponse.h>


namespace do_math
{

struct Suan
{

typedef SuanRequest Request;
typedef SuanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Suan
} // namespace do_math


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::do_math::Suan > {
  static const char* value()
  {
    return "eccb72520f9288ba7471164786064905";
  }

  static const char* value(const ::do_math::Suan&) { return value(); }
};

template<>
struct DataType< ::do_math::Suan > {
  static const char* value()
  {
    return "do_math/Suan";
  }

  static const char* value(const ::do_math::Suan&) { return value(); }
};


// service_traits::MD5Sum< ::do_math::SuanRequest> should match 
// service_traits::MD5Sum< ::do_math::Suan > 
template<>
struct MD5Sum< ::do_math::SuanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::do_math::Suan >::value();
  }
  static const char* value(const ::do_math::SuanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::do_math::SuanRequest> should match 
// service_traits::DataType< ::do_math::Suan > 
template<>
struct DataType< ::do_math::SuanRequest>
{
  static const char* value()
  {
    return DataType< ::do_math::Suan >::value();
  }
  static const char* value(const ::do_math::SuanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::do_math::SuanResponse> should match 
// service_traits::MD5Sum< ::do_math::Suan > 
template<>
struct MD5Sum< ::do_math::SuanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::do_math::Suan >::value();
  }
  static const char* value(const ::do_math::SuanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::do_math::SuanResponse> should match 
// service_traits::DataType< ::do_math::Suan > 
template<>
struct DataType< ::do_math::SuanResponse>
{
  static const char* value()
  {
    return DataType< ::do_math::Suan >::value();
  }
  static const char* value(const ::do_math::SuanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DO_MATH_MESSAGE_SUAN_H
